Added support for local AI models
narralabs/i18n-ai pull request #11
Opened 2024-08-06 05:18 UTC by scjsalva

Closes issue number #7

2024-08-06 09:00 UTC, westoque requested changes
added some feedback. 

do you also mind adding some tests? 

thank you.

2024-08-06 14:14 UTC, scjsalva commented
Hey @westoque,

I’ve added some tests for the local client and reverted the changes based on your comments. 

Thanks!

2024-08-07 10:44 UTC, westoque commented
hi @scjsalva . do you mind rebasing main and pulling latest changes there? 

there's a huge API change that will make it easier to extract the chat content, documentation here:

https://github.com/narralabs/i18n-ai/pull/12

thank you.

2024-08-12 15:00 UTC, westoque approved these changes

2024-08-12 15:09 UTC, westoque approved these changes

2024-08-12 15:09 UTC, merged