Add support for locale generation using Claude.ai
narralabs/i18n-ai pull request #5
Opened 2024-08-01 12:27 UTC by wilburhimself

fixes #2 

This pull request introduces support for Anthropic's Claude AI service alongside the existing OpenAI integration. Users can now configure their preferred AI service via environment variables. The changes include:

- New Clients: Added `AnthropicClient` and `OpenAiClient` clients under the I18nAi::Clients namespace.
- Configuration: Users can specify the AI service to use by setting the `AI_SERVICE` environment variable (anthropic for Claude, default to OpenAI).
- Middleware Update: The middleware now initializes the appropriate client based on the `AI_SERVICE` environment variable.
- Tests: Added RSpec tests for the new clients to ensure they behave as expected.

#### How to Test

1. Set the AI_SERVICE environment variable to anthropic and provide the ANTHROPIC_API_KEY.
2. Run the application and verify that translations are generated using Claude.
3. Set the AI_SERVICE environment variable to openai and provide the OPENAI_ACCESS_TOKEN.
4. Run the application and verify that translations are generated using OpenAI.
5. Run the test suite using bundle exec rspec to ensure all tests pass.

2024-08-01 15:40 UTC, westoque commented
hi @wilburhimself great work on the PR! we can finally select different AI services ❤️

would request one last change on my part, as far as configuring the client, i am voting for configuration similar to [carrierware][0].

where we can do something like this for i18n-ai:

```ruby
I18nAi.configure do |config|
  config.ai_settings = {
    provider: "openai"
    model: "gpt-4o-mini",
    access_token: ENV["OPENAI_ACCESS_TOKEN"]
  }
  config.generate_locales = [:es]
end

# this would allow us to the use anthropic
I18nAi.configure do |config|
  config.ai_settings = {
    service: "anthropic",
    model: "claude-3-haiku-20240307",
    access_token: ENV["ANTHROPIC_ACCESS_TOKEN"]
  }
  config.generate_locales = [:es]
end

# and also in the future, gemini:
I18nAi.configure do |config|
  config.ai_settings = {
    service: "gemini",
    api_key: ENV["GOOGLE_API_KEY"]
  }
  config.generate_locales = [:es]
end
```

this would give us a lot of flexibility as far as model selection and also potentially other settings.

thank you 🙇 

[0]: https://github.com/carrierwaveuploader/carrierwave?tab=readme-ov-file#using-amazon-s3

2024-08-02 17:30 UTC, wilburhimself commented
@westoque great idea! I implemented this, can you take a look?

2024-08-03 06:56 UTC, westoque requested changes
last few changes. thank you so much 🙇

2024-08-03 06:56 UTC, westoque commented on lib/i18n-ai.rb
> +    attr_accessor :configuration
do you mind putting back the old code here? seems like there's no change besides using the explicit receive `.self`?

2024-08-03 06:56 UTC, westoque commented on lib/i18n-ai/clients/anthropic_client.rb
> +        super()
do you mind removing `()` since it's an implicit function call without the `()` and more ruby-ish. thank you.

2024-08-03 06:56 UTC, westoque commented on lib/i18n-ai/clients/anthropic_client.rb
> +        nil
i believe the `puts` here will return `nil` itself so that `nil` line could be removed.

2024-08-03 06:56 UTC, westoque commented on lib/i18n-ai/clients/base_client.rb
> +    class BaseClient
great idea on adding a base class for client! ❤️

2024-08-03 06:56 UTC, westoque commented on lib/i18n-ai/clients/open_ai_client.rb
> +        super()
same comment if we can remove `()`. will put rubocop github action soon so it should handle these lint style feedback.

2024-08-03 06:56 UTC, westoque commented on lib/i18n-ai/clients/open_ai_client.rb
> +        nil
same comment above with removing the `nil` return

2024-08-03 06:56 UTC, westoque commented on lib/i18n-ai/railtie.rb
> +          raise "Unknown AI provider: #{config[:provider]}"
great use of raise here ❤️

2024-08-03 06:56 UTC, westoque commented on spec/clients/anthropic_client_spec.rb
> +RSpec.describe I18nAi::Clients::AnthropicClient do
appreciate you adding the first tests! ❤️

2024-08-03 06:56 UTC, westoque commented on README.md
> +  config.ai_settings = {
the line:

```
I18nAi.configure do |config|
  config.ai_settings = {
    provider: "openai",
    model: "gpt-4o-mini",
    access_token: ENV["OPENAI_ACCESS_TOKEN"]
  }
end
```
could be put under `### OpenAI` above

2024-08-03 06:56 UTC, westoque commented on README.md
> +I18nAi.configure do |config|
this could be put under `### Anthropic's Claude`

2024-08-04 01:26 UTC, wilburhimself commented
@westoque Thanks for the review! I updated with the changes ...

2024-08-04 01:45 UTC, merged

2024-08-04 01:45 UTC, westoque commented
@wilburhimself thank you so much. merged.